name: Workflow Scan Action
description: Scan GitHub Actions workflow files with CodeQL
inputs:
  data-path:
    description: Specifies where the data files needed by the action will be copied (must be relative to $GITHUB_WORKSPACE)
    default: .github/workflow-scan-data
runs:
  using: composite
  steps:
    - shell: bash
      env:
        DATA_PATH: ${{ inputs.data-path }}
      run: |
        mkdir -p "$DATA_PATH"
        cp "$GITHUB_ACTION_PATH"/data/* "$DATA_PATH"

        #ANALYSIS_PATHS=( "$DATA_PATH/codeql-stub.js" .github/workflows )
        #echo "${ANALYSIS_PATHS[*]}"

    - uses: github/codeql-action/init@v1
      with:
        config-file: ./${{ inputs.data-path }}/workflow-scan-config.yml 
        queries: ./${{ inputs.data-path }}/workflow-security-suite.qls
        languages: javascript
      env:
        LGTM_INDEX_INCLUDE: ${{ inputs.data-path }}/codeql-stub.js
        LGTM_INDEX_FILTERS: include:${{ inputs.data-path }}/codeql-stub.js

    - uses: github/codeql-action/analyze@v1
      env:
        LGTM_INDEX_INCLUDE: ${{ inputs.data-path }}/codeql-stub.js
        LGTM_INDEX_FILTERS: include:${{ inputs.data-path }}/codeql-stub.js
